<a href="https://colab.research.google.com/github/NikhitaB15/Machine_Learning/blob/main/machine_learning_numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
matrix= np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [7]:
add_100 = lambda i:i + 100 
add_100

<function __main__.<lambda>(i)>

In [8]:
vectorized_add_100= np.vectorize(add_100)

In [9]:
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [14]:
np.max(matrix , axis=0)


array([7, 8, 9])

In [13]:
np.min(matrix , axis=1)

array([1, 4, 7])

In [15]:
np.mean(matrix)

5.0

In [16]:
np.var(matrix)

6.666666666666667

In [17]:
np.std(matrix)

2.581988897471611

In [21]:
np.mean(matrix, axis=1)

array([2., 5., 8.])

In [41]:
matrix.reshape(1,9)

array([[1, 2, 3, 2, 4, 6, 3, 8, 9]])

In [25]:
#One useful argument in reshape is -1, which effectively means “as many as needed,”
#so reshape(-1, 1) means one row and as many columns as needed:
matrix.reshape(1, -1)
np.array([[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [26]:
matrix.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [36]:

# Flatten matrix
matrix.flatten()
matrix.trace()

14

In [31]:
np.linalg.matrix_rank(matrix)

2

In [32]:
# Create matrix
matrix = np.array([[1, 2, 3],
[2, 4, 6],
[3, 8, 9]])
# Return determinant of matrix
np.linalg.det(matrix)


0.0

In [33]:
matrix.diagonal()

array([1, 4, 9])

diagonal offset returns the diagonal above /below the main diagonal.

In [34]:
matrix.diagonal(offset=-1)

array([2, 8])

In [38]:
sum(matrix.diagonal())

14